name: Deploy Test Reports

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-reports:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build TypeScript
      run: npm run build
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
      
    - name: Run tests and generate reports
      run: npm run test:report
      env:
        HEADLESS: true
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports
        destination_dir: test-reports
        
    - name: Create test summary
      run: |
        echo "# 🧪 Test Execution Summary" > test-summary.md
        echo "" >> test-summary.md
        echo "**Date**: $(date)" >> test-summary.md
        echo "**Commit**: ${{ github.sha }}" >> test-summary.md
        echo "**Branch**: ${{ github.ref_name }}" >> test-summary.md
        echo "" >> test-summary.md
        echo "## 📊 Results" >> test-summary.md
        echo "- **Framework**: BDD Playwright + Cucumber" >> test-summary.md
        echo "- **Browsers**: Chromium, Firefox, WebKit" >> test-summary.md
        echo "- **Node.js**: 18.x, 20.x" >> test-summary.md
        echo "" >> test-summary.md
        echo "## 🔗 Links" >> test-summary.md
        echo "- [Test Reports](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/test-reports/)" >> test-summary.md
        echo "- [Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> test-summary.md
        
    - name: Upload test summary
      uses: actions/upload-artifact@v4
      with:
        name: test-summary
        path: test-summary.md
        retention-days: 30
