name: Environment Setup

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test against'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
        - development

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build TypeScript
      run: npm run build
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      
    - name: Run environment-specific tests
      run: |
        echo "Testing against ${{ github.event.inputs.environment }} environment"
        if [ "${{ github.event.inputs.environment }}" == "production" ]; then
          npm run test:smoke
        elif [ "${{ github.event.inputs.environment }}" == "staging" ]; then
          npm run test:regression
        else
          npm run test
        fi
      env:
        HEADLESS: true
        ENVIRONMENT: ${{ github.event.inputs.environment }}
        BASE_URL: ${{ github.event.inputs.environment == 'production' && 'https://demowebshop.tricentis.com' || github.event.inputs.environment == 'staging' && 'https://staging.demowebshop.tricentis.com' || 'https://dev.demowebshop.tricentis.com' }}
