name: Scheduled BDD Tests

on:
  schedule:
    # Run tests every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run'
        required: true
        default: 'smoke'
        type: choice
        options:
        - smoke
        - regression
        - performance
        - all

jobs:
  smoke-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event.inputs.test_type == 'smoke' || github.event.inputs.test_type == 'all'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build TypeScript
      run: npm run build
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
      
    - name: Run smoke tests
      run: |
        echo "Running smoke tests..."
        npm run test -- --name "Homepage loads successfully"
        npm run test -- --name "Newsletter subscription"
        npm run test -- --name "Search functionality"
      env:
        HEADLESS: true
        
    - name: Upload smoke test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: smoke-test-results
        path: reports/
        retention-days: 7

  regression-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event.inputs.test_type == 'regression' || github.event.inputs.test_type == 'all'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build TypeScript
      run: npm run build
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      
    - name: Run regression tests
      run: npm run test:report
      env:
        HEADLESS: true
        
    - name: Upload regression test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: regression-test-results
        path: reports/
        retention-days: 14

  performance-tests:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    if: github.event.inputs.test_type == 'performance' || github.event.inputs.test_type == 'all'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build TypeScript
      run: npm run build
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
      
    - name: Run performance tests
      run: |
        echo "Running performance tests..."
        npm run test -- --name "Page load performance"
        npm run test -- --name "Homepage loads successfully"
        npm run test -- --name "Featured products are displayed"
      env:
        HEADLESS: true
        
    - name: Upload performance results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: performance-test-results
        path: reports/
        retention-days: 7

  notify-results:
    runs-on: ubuntu-latest
    needs: [smoke-tests, regression-tests, performance-tests]
    if: always()
    
    steps:
    - name: Notify test completion
      run: |
        echo "Scheduled test execution completed"
        echo "Smoke tests: ${{ needs.smoke-tests.result }}"
        echo "Regression tests: ${{ needs.regression-tests.result }}"
        echo "Performance tests: ${{ needs.performance-tests.result }}"
