name: Security & Dependencies

on:
  schedule:
    # Run security checks weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level moderate
      
    - name: Check for outdated packages
      run: npm outdated || true
      
    - name: Run dependency check
      run: |
        echo "Checking for known vulnerabilities..."
        npm audit --json > audit-results.json || true
        
    - name: Upload security results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-audit-results
        path: audit-results.json
        retention-days: 30

  dependency-update:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check for updates
      run: |
        echo "Checking for package updates..."
        npm outdated --json > outdated-packages.json || true
        
    - name: Create update summary
      run: |
        if [ -f outdated-packages.json ]; then
          echo "## 📦 Package Update Summary" >> update-summary.md
          echo "" >> update-summary.md
          echo "The following packages have updates available:" >> update-summary.md
          echo "" >> update-summary.md
          echo "\`\`\`json" >> update-summary.md
          cat outdated-packages.json >> update-summary.md
          echo "\`\`\`" >> update-summary.md
        else
          echo "All packages are up to date!" > update-summary.md
        fi
        
    - name: Upload update summary
      uses: actions/upload-artifact@v4
      with:
        name: dependency-update-summary
        path: |
          update-summary.md
          outdated-packages.json
        retention-days: 7
